export { PTVClient, type PTVClientOptions } from "./client.js";

export {
  PTVError,
  PTVAuthError,
  PTVNotFoundError,
  PTVRateLimitError,
  PTVServerError,
  PTVValidationError,
  PTVNetworkError,
  PTVTimeoutError,
  errorFromStatus,
} from "./errors.js";

export type {
  // Entity types
  StatusResponse,
  Departure,
  Stop,
  Route,
  RouteType,
  RouteServiceStatus,
  Direction,
  Disruption,
  DisruptionRoute,
  DisruptionStop,
  DisruptionMode,
  Run,
  VehiclePosition,
  VehicleDescriptor,
  SearchResultStop,
  SearchResultRoute,
  SearchResultOutlet,
  Outlet,
  OutletGeolocation,
  PassengerFare,
  ZoneInfo,
  FareEstimateResultStatus,
  StopDetails,
  StopGps,
  StopLocation,
  StopAccessibility,
  StopAccessibilityWheelchair,
  StopAmenityDetails,
  // Response types
  HealthcheckResponse,
  RouteTypesResponse,
  RoutesResponse,
  RouteResponse,
  SearchResponse,
  DepartureResponse,
  StopsLocationResponse,
  StopsRouteResponse,
  StopDetailsResponse,
  DirectionsResponse,
  DisruptionsResponse,
  DisruptionResponse,
  DisruptionModesResponse,
  RunsResponse,
  RunResponse,
  FareEstimateResponse,
  OutletsResponse,
  OutletsNearbyResponse,
  StoppingPatternResponse,
  // Option types
  RoutesOptions,
  SearchOptions,
  DepartureOptions,
  NearbyOptions,
  StopsRouteOptions,
  DisruptionOptions,
  RunOptions,
  ExtendedRunOptions,
  FareEstimateOptions,
  OutletsOptions,
  StoppingPatternOptions,
  StopDetailsOptions,
} from "./types.js";
